# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Appliance-Phrasebook
version:      1.3
version_from: lib/Net/Appliance/Phrasebook.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    Data::Dumper:                  2.121
    Data::Phrasebook:              0.26
    Data::Phrasebook::Loader::YAML: 0.06
    List::MoreUtils:               0
    YAML:                          0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
